### test register page
POST http://localhost:3001/api/v1/register
Content-Type: application/json

{ 
    "email" : "cards@gmail.com",
    "password" : "testtest1*"
}

###

### test register/user page
POST http://localhost:3001/api/v1/register/user
Content-Type: application/json

{ 
    "userUID" : "user_2rl9XsWJUAb5OvlufKAxUJat4zg2",
    "username" : "apitest2"
}

###

### Get the 4 latest places (default)
GET http://localhost:3001/api/v1/chapters/latest
Content-Type: application/json

###

### Get 20 past conversations
GET http://localhost:3001/api/v1/conversation/past/1?mode=cursor&limit=20
Content-Type: application/json

### Get 20 past conversations, 2nd batch
GET http://localhost:3001/api/v1/conversation/past/1?mode=cursor&limit=20
  &cursor_unread=0
  &cursor_card=égypte8
  &cursor_swap=test
  &cursor_id=64
Content-Type: application/json