### test register page
POST http://localhost:3001/api/v1/register
Content-Type: application/json

{ 
    "email" : "cards@gmail.com",
    "password" : "testtest1*"
}

###

### test register/user page
POST http://localhost:3001/api/v1/register/user
Content-Type: application/json

{ 
    "userUID" : "user_2rl9XsWJUAb5OvlufKAxUJat4zg2",
    "username" : "apitest2"
}

###